import type { DirectionId } from "@/lib/types/startup";

export type DirectionTheme = {
  page: string;
  nav: string;
  navText: string;
  navCta: string;
  hero: string;
  heroText: string;
  heroSub: string;
  eyebrow: string;
  ctaPrimary: string;
  ctaSecondary: string;
  section: string;
  card: string;
  cardTitle: string;
  cardBody: string;
  pricingHighlight: string;
  pricingDefault: string;
  ctaBlock: string;
  footer: string;
  border: string;
};

export const DIRECTION_THEMES: Record<DirectionId, DirectionTheme> = {
  orchestra: {
    page: "bg-[#FAFBFC]",
    nav: "bg-white/95 backdrop-blur-md border-slate-100",
    navText: "text-slate-800",
    navCta: "bg-blue-600 text-white shadow-md shadow-blue-200",
    hero: "bg-gradient-to-b from-blue-50/60 to-white border-slate-100",
    heroText: "text-slate-900",
    heroSub: "text-slate-500",
    eyebrow: "bg-blue-50 border-blue-100 text-blue-700",
    ctaPrimary: "bg-blue-600 text-white shadow-lg shadow-blue-200",
    ctaSecondary: "border border-slate-200 text-slate-700 bg-white",
    section: "bg-white",
    card: "bg-white border-slate-100 shadow-sm",
    cardTitle: "text-slate-900",
    cardBody: "text-slate-500",
    pricingHighlight: "bg-blue-600 border-blue-500 text-white shadow-lg shadow-blue-200/40",
    pricingDefault: "bg-white border-slate-100 text-slate-900",
    ctaBlock: "bg-gradient-to-br from-blue-600 to-violet-500 text-white",
    footer: "bg-white border-slate-100 text-slate-400",
    border: "border-slate-100",
  },
  "premium-dark": {
    page: "bg-[#0a0a0c]",
    nav: "bg-[#0c0c0e]/95 backdrop-blur-md border-white/[0.06]",
    navText: "text-slate-200",
    navCta: "border border-white/20 text-white bg-white/[0.05]",
    hero: "bg-[#0c0c0e] border-white/[0.06]",
    heroText: "text-white font-light",
    heroSub: "text-slate-400",
    eyebrow: "border border-white/10 text-slate-400 bg-white/[0.03]",
    ctaPrimary: "border border-white/20 text-white bg-white/[0.05]",
    ctaSecondary: "text-slate-500 border-transparent bg-transparent",
    section: "bg-[#0a0a0c]",
    card: "bg-white/[0.03] border-white/[0.06]",
    cardTitle: "text-slate-200",
    cardBody: "text-slate-500",
    pricingHighlight: "border border-white/20 bg-white/[0.06] text-white",
    pricingDefault: "border-white/[0.06] bg-transparent text-slate-400",
    ctaBlock: "bg-gradient-to-r from-slate-900 via-slate-800 to-slate-900 border border-white/10 text-white",
    footer: "bg-[#0c0c0e] border-white/[0.06] text-slate-600",
    border: "border-white/[0.06]",
  },
  "bold-experimental": {
    page: "bg-white",
    nav: "bg-slate-900 border-slate-800",
    navText: "text-white",
    navCta: "bg-gradient-to-r from-orange-400 to-fuchsia-400 text-slate-900 font-bold",
    hero: "bg-gradient-to-br from-orange-50 via-fuchsia-50 to-cyan-50 border-orange-100",
    heroText: "text-slate-900",
    heroSub: "text-slate-700",
    eyebrow: "bg-gradient-to-r from-orange-500 to-fuchsia-500 text-white border-0",
    ctaPrimary: "bg-gradient-to-r from-orange-500 via-fuchsia-500 to-cyan-500 text-white shadow-lg shadow-fuchsia-200/50",
    ctaSecondary: "border-2 border-slate-900 text-slate-900 bg-white",
    section: "bg-white",
    card: "border-l-[3px] border-l-fuchsia-400 bg-fuchsia-50/50 border border-fuchsia-100",
    cardTitle: "text-slate-900 font-black",
    cardBody: "text-slate-600",
    pricingHighlight: "bg-slate-900 text-white border-slate-900",
    pricingDefault: "bg-white border-slate-200 text-slate-900",
    ctaBlock: "bg-gradient-to-r from-orange-500 to-fuchsia-600 text-white",
    footer: "bg-slate-50 border-slate-100 text-slate-500",
    border: "border-slate-100",
  },
  "minimal-clean": {
    page: "bg-white",
    nav: "bg-white border-slate-200",
    navText: "text-slate-900 font-medium",
    navCta: "bg-slate-900 text-white",
    hero: "bg-white border-slate-200",
    heroText: "text-slate-900 font-medium",
    heroSub: "text-slate-400",
    eyebrow: "text-slate-400 border-0 bg-transparent uppercase tracking-[0.2em]",
    ctaPrimary: "bg-slate-900 text-white",
    ctaSecondary: "text-slate-900 underline underline-offset-4 decoration-slate-300 border-0 bg-transparent",
    section: "bg-white",
    card: "border-0 border-b border-slate-100 bg-transparent rounded-none shadow-none",
    cardTitle: "text-slate-900 font-medium",
    cardBody: "text-slate-500",
    pricingHighlight: "border border-slate-900 bg-white text-slate-900",
    pricingDefault: "border border-slate-100 bg-white text-slate-900",
    ctaBlock: "bg-white border border-slate-200 text-slate-900",
    footer: "bg-white border-slate-200 text-slate-400",
    border: "border-slate-200",
  },
  "luxury-editorial": {
    page: "bg-[#FAF8F5]",
    nav: "bg-[#FAF8F5]/95 backdrop-blur-md border-amber-100/60",
    navText: "text-stone-800 font-serif",
    navCta: "bg-stone-900 text-amber-50",
    hero: "bg-gradient-to-b from-amber-50/40 to-[#FAF8F5] border-amber-100/40",
    heroText: "text-stone-900 font-serif",
    heroSub: "text-stone-500",
    eyebrow: "text-amber-800 border-amber-200/60 bg-amber-50/50 uppercase tracking-[0.15em] text-[10px]",
    ctaPrimary: "bg-stone-900 text-amber-50",
    ctaSecondary: "border border-stone-300 text-stone-700 bg-transparent",
    section: "bg-[#FAF8F5]",
    card: "bg-white/60 border-amber-100/50 shadow-sm",
    cardTitle: "text-stone-900 font-serif",
    cardBody: "text-stone-500",
    pricingHighlight: "bg-stone-900 text-amber-50 border-stone-800",
    pricingDefault: "bg-white border-amber-100 text-stone-900",
    ctaBlock: "bg-stone-900 text-amber-50 border border-stone-800",
    footer: "bg-[#FAF8F5] border-amber-100/40 text-stone-400",
    border: "border-amber-100/40",
  },
  "glass-futuristic": {
    page: "bg-gradient-to-br from-slate-900 via-indigo-950 to-slate-900",
    nav: "bg-white/5 backdrop-blur-xl border-white/10",
    navText: "text-slate-200",
    navCta: "bg-cyan-400/20 text-cyan-200 border border-cyan-400/30 backdrop-blur-md",
    hero: "bg-transparent border-white/5",
    heroText: "text-white",
    heroSub: "text-slate-400",
    eyebrow: "bg-white/10 text-cyan-300 border border-white/10 backdrop-blur-md",
    ctaPrimary: "bg-cyan-500/80 text-white backdrop-blur-md shadow-lg shadow-cyan-500/20",
    ctaSecondary: "border border-white/20 text-slate-300 bg-white/5 backdrop-blur-md",
    section: "bg-transparent",
    card: "bg-white/5 border-white/10 backdrop-blur-md",
    cardTitle: "text-white",
    cardBody: "text-slate-400",
    pricingHighlight: "bg-cyan-500/20 border-cyan-400/30 text-white backdrop-blur-md",
    pricingDefault: "bg-white/5 border-white/10 text-slate-300",
    ctaBlock: "bg-gradient-to-r from-cyan-500/30 to-violet-500/30 border border-white/10 text-white backdrop-blur-xl",
    footer: "bg-transparent border-white/5 text-slate-600",
    border: "border-white/10",
  },
  "creator-playful": {
    page: "bg-gradient-to-b from-pink-50 to-white",
    nav: "bg-white/90 backdrop-blur-md border-pink-100",
    navText: "text-slate-800",
    navCta: "bg-gradient-to-r from-pink-500 to-violet-500 text-white font-bold",
    hero: "bg-gradient-to-br from-pink-50 via-violet-50 to-amber-50 border-pink-100",
    heroText: "text-slate-900",
    heroSub: "text-slate-600",
    eyebrow: "bg-pink-100 text-pink-700 border-pink-200",
    ctaPrimary: "bg-gradient-to-r from-pink-500 to-violet-500 text-white shadow-lg shadow-pink-200",
    ctaSecondary: "border-2 border-pink-200 text-pink-700 bg-white",
    section: "bg-white/50",
    card: "bg-white border-pink-100 shadow-md shadow-pink-100/50 rounded-3xl",
    cardTitle: "text-slate-900 font-bold",
    cardBody: "text-slate-500",
    pricingHighlight: "bg-gradient-to-br from-pink-500 to-violet-500 text-white border-0",
    pricingDefault: "bg-white border-pink-100 text-slate-900",
    ctaBlock: "bg-gradient-to-r from-pink-500 via-violet-500 to-amber-400 text-white",
    footer: "bg-pink-50/50 border-pink-100 text-slate-400",
    border: "border-pink-100",
  },
  "apple-modern": {
    page: "bg-[#FBFBFD]",
    nav: "bg-[#FBFBFD]/80 backdrop-blur-2xl border-slate-200/60",
    navText: "text-slate-900 font-medium tracking-tight",
    navCta: "bg-blue-600 text-white rounded-full",
    hero: "bg-[#FBFBFD] border-slate-200/60",
    heroText: "text-slate-900 font-semibold tracking-tight",
    heroSub: "text-slate-500 font-light",
    eyebrow: "text-blue-600 bg-transparent border-0 font-medium",
    ctaPrimary: "bg-blue-600 text-white rounded-full shadow-none",
    ctaSecondary: "text-blue-600 bg-transparent border-0 font-medium",
    section: "bg-[#FBFBFD]",
    card: "bg-white border-slate-200/60 shadow-sm rounded-2xl",
    cardTitle: "text-slate-900 font-semibold",
    cardBody: "text-slate-500 font-light",
    pricingHighlight: "bg-white border-2 border-blue-600 text-slate-900 shadow-xl",
    pricingDefault: "bg-white border-slate-200/60 text-slate-900",
    ctaBlock: "bg-slate-900 text-white rounded-3xl",
    footer: "bg-[#FBFBFD] border-slate-200/60 text-slate-400",
    border: "border-slate-200/60",
  },
  "retro-tech": {
    page: "bg-[#F5F0E8]",
    nav: "bg-[#2D4A3E] border-[#1a2e25]",
    navText: "text-emerald-100 font-mono text-xs",
    navCta: "bg-emerald-400 text-[#1a2e25] font-mono font-bold",
    hero: "bg-[#2D4A3E] border-[#1a2e25]",
    heroText: "text-emerald-50 font-mono",
    heroSub: "text-emerald-300/80 font-mono text-sm",
    eyebrow: "text-emerald-400 border border-emerald-600/40 bg-emerald-950/30 font-mono",
    ctaPrimary: "bg-emerald-400 text-[#1a2e25] font-mono font-bold",
    ctaSecondary: "border border-emerald-600/40 text-emerald-300 font-mono bg-transparent",
    section: "bg-[#F5F0E8]",
    card: "bg-[#EDE8DF] border-[#C4BAA8] font-mono",
    cardTitle: "text-[#2D4A3E] font-mono font-bold",
    cardBody: "text-[#5C6B62] font-mono text-xs",
    pricingHighlight: "bg-[#2D4A3E] border-[#1a2e25] text-emerald-100 font-mono",
    pricingDefault: "bg-[#EDE8DF] border-[#C4BAA8] text-[#2D4A3E] font-mono",
    ctaBlock: "bg-[#2D4A3E] text-emerald-100 border border-emerald-600/30 font-mono",
    footer: "bg-[#EDE8DF] border-[#C4BAA8] text-[#5C6B62] font-mono text-xs",
    border: "border-[#C4BAA8]",
  },
  "creative-agency": {
    page: "bg-white",
    nav: "bg-violet-600 border-violet-700",
    navText: "text-white font-black uppercase tracking-wider text-xs",
    navCta: "bg-yellow-400 text-violet-900 font-black uppercase",
    hero: "bg-violet-600 border-violet-700",
    heroText: "text-white font-black uppercase tracking-tight",
    heroSub: "text-violet-200",
    eyebrow: "bg-yellow-400 text-violet-900 font-black uppercase",
    ctaPrimary: "bg-yellow-400 text-violet-900 font-black uppercase",
    ctaSecondary: "border-2 border-white text-white font-bold uppercase bg-transparent",
    section: "bg-white",
    card: "border-l-4 border-l-violet-600 bg-violet-50 border border-violet-100",
    cardTitle: "text-violet-900 font-black",
    cardBody: "text-slate-600",
    pricingHighlight: "bg-violet-600 text-white border-violet-700 font-black",
    pricingDefault: "bg-white border-violet-200 text-violet-900",
    ctaBlock: "bg-violet-600 text-white border-4 border-yellow-400",
    footer: "bg-violet-50 border-violet-100 text-violet-400",
    border: "border-violet-100",
  },
  "fashion-ai": {
    page: "bg-black",
    nav: "bg-black border-white/10",
    navText: "text-white font-light tracking-[0.2em] uppercase text-xs",
    navCta: "border border-white text-white uppercase tracking-widest text-xs px-6",
    hero: "bg-black border-white/10",
    heroText: "text-white font-light tracking-tight",
    heroSub: "text-neutral-400 font-light",
    eyebrow: "text-rose-400 border-0 bg-transparent uppercase tracking-[0.3em] text-[10px]",
    ctaPrimary: "bg-white text-black uppercase tracking-widest text-xs font-medium",
    ctaSecondary: "text-white border-b border-white/30 rounded-none bg-transparent uppercase tracking-widest text-xs",
    section: "bg-neutral-950",
    card: "bg-neutral-900 border-white/5",
    cardTitle: "text-white font-light",
    cardBody: "text-neutral-500 font-light",
    pricingHighlight: "bg-white text-black border-white font-light",
    pricingDefault: "bg-neutral-900 border-white/10 text-neutral-400 font-light",
    ctaBlock: "bg-neutral-900 border border-white/10 text-white font-light",
    footer: "bg-black border-white/10 text-neutral-600 font-light",
    border: "border-white/10",
  },
  "genz-vibrant": {
    page: "bg-lime-50",
    nav: "bg-black border-black",
    navText: "text-lime-400 font-black",
    navCta: "bg-lime-400 text-black font-black rotate-0",
    hero: "bg-lime-400 border-black border-b-4",
    heroText: "text-black font-black",
    heroSub: "text-black/70 font-bold",
    eyebrow: "bg-black text-lime-400 font-black border-2 border-black",
    ctaPrimary: "bg-black text-lime-400 font-black border-2 border-black",
    ctaSecondary: "bg-white text-black font-black border-2 border-black",
    section: "bg-lime-50",
    card: "bg-white border-2 border-black shadow-[4px_4px_0_0_#000]",
    cardTitle: "text-black font-black",
    cardBody: "text-black/60 font-medium",
    pricingHighlight: "bg-black text-lime-400 border-2 border-black shadow-[4px_4px_0_0_#84cc16]",
    pricingDefault: "bg-white border-2 border-black text-black",
    ctaBlock: "bg-black text-lime-400 border-4 border-lime-400 font-black",
    footer: "bg-lime-100 border-black/10 text-black/50 font-bold",
    border: "border-black/10",
  },
  "cinematic-ai": {
    page: "bg-[#0f0f12]",
    nav: "bg-[#0f0f12]/90 backdrop-blur-md border-indigo-900/30",
    navText: "text-indigo-100",
    navCta: "bg-indigo-600 text-white shadow-lg shadow-indigo-900/50",
    hero: "bg-gradient-to-b from-indigo-950/80 to-[#0f0f12] border-indigo-900/20",
    heroText: "text-white font-light",
    heroSub: "text-indigo-300/70",
    eyebrow: "text-indigo-400 border border-indigo-800/50 bg-indigo-950/50",
    ctaPrimary: "bg-indigo-600 text-white shadow-xl shadow-indigo-900/40",
    ctaSecondary: "border border-indigo-700/50 text-indigo-300 bg-indigo-950/30",
    section: "bg-[#0f0f12]",
    card: "bg-indigo-950/20 border-indigo-900/30",
    cardTitle: "text-indigo-100",
    cardBody: "text-indigo-400/70",
    pricingHighlight: "bg-indigo-600/20 border-indigo-500/40 text-white shadow-xl shadow-indigo-900/30",
    pricingDefault: "bg-indigo-950/10 border-indigo-900/20 text-indigo-400",
    ctaBlock: "bg-gradient-to-r from-indigo-900 via-violet-900 to-indigo-900 border border-indigo-700/30 text-white",
    footer: "bg-[#0a0a0d] border-indigo-900/20 text-indigo-600",
    border: "border-indigo-900/20",
  },
  "minimal-luxury": {
    page: "bg-[#F7F6F3]",
    nav: "bg-[#F7F6F3] border-stone-200/80",
    navText: "text-stone-700 font-light tracking-wide",
    navCta: "bg-stone-800 text-stone-50 font-light tracking-wide",
    hero: "bg-[#F7F6F3] border-stone-200/80",
    heroText: "text-stone-800 font-light tracking-tight",
    heroSub: "text-stone-400 font-light",
    eyebrow: "text-stone-400 border-0 bg-transparent tracking-[0.25em] uppercase text-[10px] font-light",
    ctaPrimary: "bg-stone-800 text-stone-50 font-light tracking-wide",
    ctaSecondary: "text-stone-600 border-b border-stone-300 rounded-none bg-transparent font-light",
    section: "bg-[#F7F6F3]",
    card: "bg-white/80 border-stone-200/60 shadow-none",
    cardTitle: "text-stone-800 font-light",
    cardBody: "text-stone-400 font-light",
    pricingHighlight: "bg-stone-800 text-stone-50 border-stone-800 font-light",
    pricingDefault: "bg-white border-stone-200/80 text-stone-700 font-light",
    ctaBlock: "bg-stone-800 text-stone-50 font-light tracking-wide",
    footer: "bg-[#F7F6F3] border-stone-200/80 text-stone-400 font-light",
    border: "border-stone-200/80",
  },
};
