/**
 * Premium Dark concept variants — ALL world-intelligence categories.
 * Selected via seed + brief in concept-rotation-pools.ts (not fruit-only).
 */

import type { CreativeConcept } from "./engine";

type VariantConcepts = Record<string, CreativeConcept>;

const SOFTWARE_SAAS: VariantConcepts = {
  "software-saas::premium-dark": {
    coreIdea: "Software that disappears into the work — invisible until indispensable.",
    emotion: "trust",
    tension: { force1: "complex capability", force2: "effortless interface" },
    heroMoment: "Dashboard at night — one metric climbing, everything else quiet.",
    typeAttitude: "Clean sans-serif. Confident, never loud. Product screenshots earn their place.",
    imageTreatmentRule: "UI in context, dark environments, subtle glow. No stock hand-on-laptop clichés.",
    pacingMetaphor: "Onboarding that respects your time.",
    densityFeeling: "Features first, then proof — balanced editorial rhythm.",
  },
  "software-saas::premium-dark-enterprise": {
    coreIdea: "Enterprise software should feel inevitable, not intimidating.",
    emotion: "controlled intensity",
    tension: { force1: "institutional scale", force2: "human clarity" },
    heroMoment: "War room wall of monitors — one pipeline green, the rest irrelevant.",
    typeAttitude: "Mono labels, large numerals. Authority through restraint.",
    imageTreatmentRule: "Cool tone, high clarity, abstract workspace atmospheres.",
    pacingMetaphor: "Watching game film — pause, rewind, decide.",
    densityFeeling: "Data-dense proof sections between atmospheric breathers.",
  },
  "software-saas::premium-dark-startup": {
    coreIdea: "Move fast, but look like you already won.",
    emotion: "creative hunger",
    tension: { force1: "scrappy speed", force2: "premium polish" },
    heroMoment: "Founder laptop at 2am — shipping glow on their face, not the screen.",
    typeAttitude: "Conversational headlines. Bold CTAs. Feels like momentum.",
    imageTreatmentRule: "Warm LED, real desks, film grain. Builder energy.",
    pacingMetaphor: "The first hour of a productive session.",
    densityFeeling: "Medium density with visual surprises every third section.",
  },
  "software-saas::premium-dark-ai": {
    coreIdea: "AI that feels like intelligence, not magic tricks.",
    emotion: "precision",
    tension: { force1: "black-box power", force2: "transparent control" },
    heroMoment: "Neural visualization as art — nodes pulsing on obsidian.",
    typeAttitude: "Thin tracked type. Technical eyebrows. Numbers as poetry.",
    imageTreatmentRule: "Abstract data viz, macro UI detail, cold precision lighting.",
    pacingMetaphor: "Stepped reveals — each scroll unlocks capability.",
    densityFeeling: "One big idea per screen, then dense capability proof.",
  },
  "software-saas::premium-dark-minimal": {
    coreIdea: "One job. Done perfectly. Nothing else on screen.",
    emotion: "clarity",
    tension: { force1: "feature temptation", force2: "ruthless focus" },
    heroMoment: "Single UI panel floating on black — one action, one outcome.",
    typeAttitude: "Light weight type on dark ground. Maximum breathing room.",
    imageTreatmentRule: "Isolated product shots, no clutter, soft rim light.",
    pacingMetaphor: "Getting dressed slowly because you know you look good.",
    densityFeeling: "Radical sparsity — almost nothing at once.",
  },
};

const FINANCE_FINTECH: VariantConcepts = {
  "finance-fintech::premium-dark": {
    coreIdea: "Money is emotional — the interface must be calm enough to trust.",
    emotion: "trust",
    tension: { force1: "financial anxiety", force2: "designed calm" },
    heroMoment: "Balance graph smoothing upward — green accent on charcoal.",
    typeAttitude: "Stable serif headlines. Reassuring subcopy. Never hype.",
    imageTreatmentRule: "Abstract finance textures, no cash fan photos. UI-forward.",
    pacingMetaphor: "Breathing in. Breathing out.",
    densityFeeling: "Sparse trust-building, then dense security proof.",
  },
  "finance-fintech::premium-dark-disruptor": {
    coreIdea: "Banking is broken — we look like the break.",
    emotion: "aggression",
    tension: { force1: "legacy institutions", force2: "radical simplicity" },
    heroMoment: "Credit card slicing through marble — metaphor made literal.",
    typeAttitude: "ALL CAPS moments. Sharp sans. Confrontational clarity.",
    imageTreatmentRule: "High contrast, bold crops, neon accent on black.",
    pacingMetaphor: "Fast breaks. Zero transition.",
    densityFeeling: "Information overload as confidence.",
  },
  "finance-fintech::premium-dark-wealth": {
    coreIdea: "Wealth management is stewardship, not spectacle.",
    emotion: "reverence",
    tension: { force1: "generational capital", force2: "modern access" },
    heroMoment: "Single gold line graph on black — decades compressed into one curve.",
    typeAttitude: "Serif display, wide tracking. Whisper, never shout.",
    imageTreatmentRule: "Dark luxury, subtle metal tones, no lifestyle flex.",
    pacingMetaphor: "A long read in a quiet room.",
    densityFeeling: "Sparse sections that feel full through restraint.",
  },
  "finance-fintech::premium-dark-consumer": {
    coreIdea: "Finance for humans who hate finance apps.",
    emotion: "joyful ownership",
    tension: { force1: "money stress", force2: "playful control" },
    heroMoment: "Phone showing savings goal hit — confetti implied, not shown.",
    typeAttitude: "Friendly, lowercase moments. Celebration without cringe.",
    imageTreatmentRule: "Bright UI on dark frame, warm accents, approachable.",
    pacingMetaphor: "Scrolling a feed that actually helps you.",
    densityFeeling: "Packed cards, short beats, constant forward motion.",
  },
};

const SPORTS_ANALYTICS: VariantConcepts = {
  "sports-analytics::premium-dark-arena": {
    coreIdea: "The arena never sleeps — neither does the intelligence layer.",
    emotion: "aggression",
    tension: { force1: "raw competition", force2: "cold analytics" },
    heroMoment: "Empty court, overhead lights, heatmap ghosted on hardwood.",
    typeAttitude: "Impact weight. Stats as headlines.",
    imageTreatmentRule: "Arena environments, never faces. Data composited in-world.",
    pacingMetaphor: "Fast breaks. Immediate.",
    densityFeeling: "Maximal energy opening, dense proof mid-scroll.",
  },
  "sports-analytics::premium-dark-film-room": {
    coreIdea: "Every championship team lives in the film room.",
    emotion: "controlled intensity",
    tension: { force1: "athletic instinct", force2: "analytical rigor" },
    heroMoment: "Coach silhouette before six screens of play breakdown.",
    typeAttitude: "Mono-spaced labels. Numbers dominate.",
    imageTreatmentRule: "Moody court photography, dashboard UI, bench details.",
    pacingMetaphor: "Watching game film — pause and rewind.",
    densityFeeling: "Data-dense with atmospheric punctuation.",
  },
  "sports-analytics::premium-dark-fan": {
    coreIdea: "Fans feel the game — we make that feeling measurable.",
    emotion: "visceral excitement",
    tension: { force1: "crowd energy", force2: "personal insight" },
    heroMoment: "Stadium blur — scoreboard sharp, everything else kinetic.",
    typeAttitude: "Bold sans, high energy subheads.",
    imageTreatmentRule: "Motion blur, saturated team colors, crowd atmosphere.",
    pacingMetaphor: "Biting into something cold and ripe — instant hit.",
    densityFeeling: "Colliding image sections, no comfortable pauses.",
  },
};

const FASHION: VariantConcepts = {
  "fashion-apparel::premium-dark": {
    coreIdea: "Fashion at night — desire amplified by darkness.",
    emotion: "desire",
    tension: { force1: "the body", force2: "the garment" },
    heroMoment: "Back-turned model, coat only, full bleed, no headline.",
    typeAttitude: "One or two words. Tall thin serif. Bottom-left placement.",
    imageTreatmentRule: "Editorial motion, studio drama, never catalog white.",
    pacingMetaphor: "Walking through a museum — stop when compelled.",
    densityFeeling: "One image per screen. Silence is luxury.",
  },
  "fashion-apparel::premium-dark-street": {
    coreIdea: "Streetwear is culture speed — the site must keep up.",
    emotion: "visceral excitement",
    tension: { force1: "underground energy", force2: "premium craft" },
    heroMoment: "Sneaker mid-air, concrete background, flash photography.",
    typeAttitude: "Impact caps, mixed scale, collage energy.",
    imageTreatmentRule: "High contrast, urban texture, saturated accents.",
    pacingMetaphor: "Fast breaks through a drop.",
    densityFeeling: "Grid-breaking density, drops as rhythm.",
  },
  "fashion-apparel::premium-dark-couture": {
    coreIdea: "Couture is architecture for the body.",
    emotion: "reverence",
    tension: { force1: "sculptural form", force2: "human warmth" },
    heroMoment: "Fabric detail macro — thread like gold on black velvet.",
    typeAttitude: "Serif honey. Wide breathing. Never hurried.",
    imageTreatmentRule: "Macro textile, rim light, deep shadows.",
    pacingMetaphor: "The pace of someone about to eat something perfect.",
    densityFeeling: "Sparse — each image earns a full viewport.",
  },
  "fashion-apparel::premium-dark-minimal": {
    coreIdea: "The garment is the only color in a monochrome world.",
    emotion: "creative hunger",
    tension: { force1: "absence", force2: "want" },
    heroMoment: "White shirt on black — only shadow defines the form.",
    typeAttitude: "Light weight, extreme leading, tracked caps.",
    imageTreatmentRule: "Single subject, negative space, precise light.",
    pacingMetaphor: "Getting dressed slowly.",
    densityFeeling: "One product, one sentence, repeat.",
  },
};

const CREATOR: VariantConcepts = {
  "creator-tools::premium-dark": {
    coreIdea: "Creators work in the dark — their tools should glow with them.",
    emotion: "creative hunger",
    tension: { force1: "the grind", force2: "the payoff" },
    heroMoment: "Ring light halo — creator mid-edit, analytics climbing on second monitor.",
    typeAttitude: "Conversational, lowercase warmth, bold CTAs.",
    imageTreatmentRule: "Real setups, cables, notebooks, warm LED, film grain.",
    pacingMetaphor: "First hour of a productive session.",
    densityFeeling: "Visual pops every third section.",
  },
  "creator-tools::premium-dark-analytics": {
    coreIdea: "Creators are CEOs — they need CEO-grade dashboards.",
    emotion: "controlled intensity",
    tension: { force1: "art instinct", force2: "growth metrics" },
    heroMoment: "Analytics spike overlaid on timeline editor — art meets data.",
    typeAttitude: "Numbers large, labels small. Dashboard native.",
    imageTreatmentRule: "UI-forward, dark studio, metric highlights.",
    pacingMetaphor: "Stepped scroll through capability layers.",
    densityFeeling: "Dense feature proof, atmospheric hero.",
  },
  "creator-tools::premium-dark-community": {
    coreIdea: "Creators don't grow alone — community is the product.",
    emotion: "joyful ownership",
    tension: { force1: "solo craft", force2: "shared momentum" },
    heroMoment: "Grid of creator faces — diverse, mid-laugh, same platform glow.",
    typeAttitude: "Social-native hierarchy. Feels like a DM.",
    imageTreatmentRule: "Warm, slightly overexposed, authentic environments.",
    pacingMetaphor: "Scrolling a great grid at 2am.",
    densityFeeling: "Packed social proof, fast handoffs.",
  },
};

const WELLNESS: VariantConcepts = {
  "wellness-mindfulness::premium-dark": {
    coreIdea: "Stillness is radical — we design for the pause.",
    emotion: "permission",
    tension: { force1: "modern urgency", force2: "ancient slowness" },
    heroMoment: "Figure small in misty valley — full width, no words for seconds.",
    typeAttitude: "Thin, tracked, never urgent. Every sentence a breath.",
    imageTreatmentRule: "Outdoor dawn/dusk, lifted blacks, desaturated calm.",
    pacingMetaphor: "Meditation — the pause is the product.",
    densityFeeling: "Radical sparsity, one dense proof, return to stillness.",
  },
  "wellness-mindfulness::premium-dark-modern": {
    coreIdea: "Calm technology — the app disappears, the feeling stays.",
    emotion: "trust",
    tension: { force1: "digital noise", force2: "designed silence" },
    heroMoment: "Phone showing timer — infinite white space around it on black.",
    typeAttitude: "Light weight, generous leading, soft confidence.",
    imageTreatmentRule: "Clean product in context, soft gradients.",
    pacingMetaphor: "Breathing in. Breathing out.",
    densityFeeling: "Barely anything on screen at once.",
  },
  "wellness-mindfulness::premium-dark-retreat": {
    coreIdea: "Retreat is not escape — it's return.",
    emotion: "contemplation",
    tension: { force1: "wild landscape", force2: "curated comfort" },
    heroMoment: "Hot spring steam at blue hour — figure optional.",
    typeAttitude: "Tall serif, wide spacing, editorial patience.",
    imageTreatmentRule: "Landscape editorial, golden/blue hour, film grain.",
    pacingMetaphor: "A long read in a quiet room.",
    densityFeeling: "One image per screen alternates with text.",
  },
};

const FOOD_BEVERAGE: VariantConcepts = {
  "food-beverage::premium-dark": {
    coreIdea: "The table is theater — every dish a scene.",
    emotion: "reverence",
    tension: { force1: "chef craft", force2: "dark stage" },
    heroMoment: "Plated dish, single spotlight, steam rising on black.",
    typeAttitude: "Serif elegance. Menu as poetry.",
    imageTreatmentRule: "Michelin plating, rim light, no busy backgrounds.",
    pacingMetaphor: "Course by course — unhurried.",
    densityFeeling: "Sparse luxury beats between menu sections.",
  },
  "food-beverage::premium-dark-neighborhood": {
    coreIdea: "Your corner spot — elevated but never pretentious.",
    emotion: "organic warmth",
    tension: { force1: "neighborhood soul", force2: "modern delivery" },
    heroMoment: "Bistro window glow — rain outside, warmth inside.",
    typeAttitude: "Warm serif, conversational copy.",
    imageTreatmentRule: "Warm grain, amber light, candid dining.",
    pacingMetaphor: "Sunday morning before crowds.",
    densityFeeling: "Story and sourcing weave together.",
  },
  "food-beverage::premium-dark-nightlife": {
    coreIdea: "Cocktails are liquid architecture.",
    emotion: "visceral excitement",
    tension: { force1: "night energy", force2: "precise craft" },
    heroMoment: "Cocktail pour mid-stream — neon rim, black bar.",
    typeAttitude: "Bold sans, neon accent type moments.",
    imageTreatmentRule: "High saturation, bar atmosphere, motion.",
    pacingMetaphor: "Fast breaks between beats.",
    densityFeeling: "Dense, kinetic, no dead air.",
  },
};

const HEALTH: VariantConcepts = {
  "health-medical::premium-dark": {
    coreIdea: "Healthcare deserves dignity — not clinical anxiety.",
    emotion: "trust",
    tension: { force1: "medical complexity", force2: "human reassurance" },
    heroMoment: "Clean clinic corridor — light at the end, calm not sterile.",
    typeAttitude: "Stable, accessible, never alarming.",
    imageTreatmentRule: "Soft clinical, real environments, diverse patients implied not staged.",
    pacingMetaphor: "Breathing in. Breathing out.",
    densityFeeling: "Trust first, proof dense, CTA gentle.",
  },
  "health-medical::premium-dark-precision": {
    coreIdea: "Precision medicine — personal, not generic.",
    emotion: "precision",
    tension: { force1: "genomic complexity", force2: "clear action" },
    heroMoment: "DNA helix as light sculpture on dark — beauty in data.",
    typeAttitude: "Technical clarity. Thin tracked labels.",
    imageTreatmentRule: "Macro medical detail, cool tone, abstract science.",
    pacingMetaphor: "Stepped capability reveals.",
    densityFeeling: "One revelation per scroll.",
  },
  "health-medical::premium-dark-compassion": {
    coreIdea: "Healing is human connection first.",
    emotion: "permission",
    tension: { force1: "vulnerability", force2: "professional care" },
    heroMoment: "Hands holding — not faces — warm light on dark.",
    typeAttitude: "Soft, slow, generous line height.",
    imageTreatmentRule: "Intimate, warm, no stock smiles.",
    pacingMetaphor: "Meditation pace.",
    densityFeeling: "Sparse emotional beats.",
  },
};

const EDUCATION: VariantConcepts = {
  "education-learning::premium-dark": {
    coreIdea: "Learning should feel like discovery, not homework.",
    emotion: "creative hunger",
    tension: { force1: "curiosity", force2: "structured path" },
    heroMoment: "Student lit by laptop — notes everywhere, focus absolute.",
    typeAttitude: "Encouraging, clear, momentum-building.",
    imageTreatmentRule: "Real study environments, warm desk light.",
    pacingMetaphor: "First hour of flow state.",
    densityFeeling: "Feature rhythm with social proof pockets.",
  },
  "education-learning::premium-dark-institutional": {
    coreIdea: "Institutions evolve — credibility meets innovation.",
    emotion: "trust",
    tension: { force1: "academic tradition", force2: "digital transformation" },
    heroMoment: "Campus aerial at dusk — one building lit for night class.",
    typeAttitude: "Serif authority, measured pace.",
    imageTreatmentRule: "Campus architecture, library atmosphere.",
    pacingMetaphor: "Long read, respected pace.",
    densityFeeling: "Editorial alternation.",
  },
  "education-learning::premium-dark-playful": {
    coreIdea: "Learning is play for people who forgot it's allowed.",
    emotion: "joyful ownership",
    tension: { force1: "game energy", force2: "real skill" },
    heroMoment: "Gamified progress bar hitting 100% — confetti implied.",
    typeAttitude: "Mixed scale, fun without childish.",
    imageTreatmentRule: "Bright UI accents on dark, colorful illustrations ok.",
    pacingMetaphor: "Instagram grid energy.",
    densityFeeling: "Short beats, constant reward.",
  },
};

const HOME: VariantConcepts = {
  "home-living::premium-dark": {
    coreIdea: "Home is the ultimate editorial — lived in, not staged.",
    emotion: "contemplation",
    tension: { force1: "designed perfection", force2: "authentic living" },
    heroMoment: "Living room at dusk — one lamp, long shadows, no people.",
    typeAttitude: "Serif quiet, magazine pacing.",
    imageTreatmentRule: "Interior editorial, warm tungsten, wide shots.",
    pacingMetaphor: "Walking through a museum.",
    densityFeeling: "One room per screen.",
  },
  "home-living::premium-dark-modernist": {
    coreIdea: "Modernism is honesty — form follows how you actually live.",
    emotion: "precision",
    tension: { force1: "geometric order", force2: "human softness" },
    heroMoment: "Concrete and glass — one plant, one chair, perfect light.",
    typeAttitude: "Geometric sans, strict grid.",
    imageTreatmentRule: "Architectural photography, cool tone, minimal props.",
    pacingMetaphor: "Stepped gallery walk.",
    densityFeeling: "Sparse, grid-locked.",
  },
  "home-living::premium-dark-cozy": {
    coreIdea: "Cozy is a design decision — warmth engineered.",
    emotion: "organic warmth",
    tension: { force1: "hygge texture", force2: "modern commerce" },
    heroMoment: "Knit throw, firelight, coffee steam — tactile close-up.",
    typeAttitude: "Soft serif, invitation not sales.",
    imageTreatmentRule: "Warm grain, amber, macro textiles.",
    pacingMetaphor: "Sunday morning market.",
    densityFeeling: "Story-led, sourcing woven in.",
  },
};

const TRAVEL: VariantConcepts = {
  "travel-experience::premium-dark": {
    coreIdea: "Travel is transformation — the site should feel like departure.",
    emotion: "desire",
    tension: { force1: "wanderlust", force2: "curated ease" },
    heroMoment: "Airplane window — clouds below, golden hour, infinite horizon.",
    typeAttitude: "Serif wanderlust. Evocative, not brochure.",
    imageTreatmentRule: "Landscape cinematic, golden hour, no tourist crowds.",
    pacingMetaphor: "Long read in a quiet room.",
    densityFeeling: "Atmospheric dominates, proof sparse.",
  },
  "travel-experience::premium-dark-adventure": {
    coreIdea: "Adventure is the point — comfort is how you recover.",
    emotion: "visceral excitement",
    tension: { force1: "raw terrain", force2: "expert guidance" },
    heroMoment: "Cliff edge trail — boots forward, valley infinite.",
    typeAttitude: "Bold sans, action verbs.",
    imageTreatmentRule: "Wide landscape, motion, saturated nature.",
    pacingMetaphor: "Fast breaks between vistas.",
    densityFeeling: "Kinetic collage of destinations.",
  },
  "travel-experience::premium-dark-luxury": {
    coreIdea: "Luxury travel is time reclaimed.",
    emotion: "reverence",
    tension: { force1: "exclusive access", force2: "effortless logistics" },
    heroMoment: "Private villa pool at night — stars, silence, one light.",
    typeAttitude: "Whisper serif. Extreme restraint.",
    imageTreatmentRule: "Dark luxury, minimal people, architectural hospitality.",
    pacingMetaphor: "Glacial, museum pace.",
    densityFeeling: "One vista per viewport.",
  },
};

/** All category variants — merged into CREATIVE_CONCEPTS */
export const CATEGORY_PREMIUM_DARK_VARIANTS: VariantConcepts = {
  ...SOFTWARE_SAAS,
  ...FINANCE_FINTECH,
  ...SPORTS_ANALYTICS,
  ...FASHION,
  ...CREATOR,
  ...WELLNESS,
  ...FOOD_BEVERAGE,
  ...HEALTH,
  ...EDUCATION,
  ...HOME,
  ...TRAVEL,
};
